#!/usr/bin/env bash
# Bash script that installs Nginx server
sudo pt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html >/dev/null
sudo service nginx start