#!/usr/bin/env bash
# this script install's nginx and craetes a file 'Hello world' and run's the nginx server

sudo su
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start