#!/usr/bin/env bash
# Configure Nginx server

# Install nginx
sudo apt-get update
sudo apt-get install -y nginx


# add the following configuration to the existing server block
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx
service nginx restart
