#!/usr/bin/env bash
# This script configures your Nginx server to have a custom 404 page that contains the string "Ceci n'est pas une page."

sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start

echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

conf_new="server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}"

echo "$conf_new" | sudo tee /etc/nginx/sites-available/default > /dev/null
sudo service nginx restart
