#!/usr/bin/env bash
#configure a custom 404 page

sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
chmod -R 755 /var/www/html
echo 'Hello World' | sudo tee /var/www/html/index.html > /dev/null

new_config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
               root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }
        error_page 404 /404.html;
        location  /404.html {
            internal;
        }
}
"
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "$new_config" | sudo tee /etc/nginx/sites-available/default > /dev/null

if [ "$(pgrep nginx)" -le 0 ];
then
    sudo service nginx start
else
    sudo service nginx restart
fi;