#!/usr/bin/env bash
# this is a script that generates a MySQL dump and creates a compressed archive out of it.
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"
mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$file_name" backup.sql
