#!/usr/bin/env bash
# im the king of all the kings ^_^
echo $$ >> /var/run/myscript.pid
trap "echo Y U no love me?!" SIGINT
trap "echo I hate the kill command && rm -rf /var/run/myscript.pid; exit" SIGTERM SIGQUIT
while :
do 
    echo "To Infinity in beyond"
    sleep 2
done