#!/usr/bin/env bash
# will do the thing you know what i mean im the king of all time im the shark ^-^
while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done