#!/usr/bin/env bash
# This bash script uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.
# key ~/.ssh/school with the user ubuntu
ssh ubuntu@100.25.19.204 -i ~/.ssh/school

